### ISSUE TITLE
Does this library work with @material-ui next?

### ISSUE THREAD

**Issue by felixakiragreen** [parkerself22/mui-table#2]
My apologies for not testing it first.

Currently using `@next` release: `@material-ui/core@v4.0.0-alpha.3`. Can I use this library or should I wait for 4.0 to be officially supported?

**Comment by wroughtec** [comment]
Doesn't look like it there are a few breaking changes (with @next) that currently stop it working with the v4

**Comment by felixakiragreen** [comment]
Thanks!
